// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htaxjtompoazrhrlfatq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0YXhqdG9tcG9henJocmxmYXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMTkwNDgsImV4cCI6MjA1NTY5NTA0OH0.Q7ugXzdqsGP9vHMyDoqqhK7Q1eKhGz7XgNiiAR4EPQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);